[2025-08-12T15:47:04.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T15:47:04.329+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T14:00:00+00:00 [queued]>
[2025-08-12T15:47:04.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T14:00:00+00:00 [queued]>
[2025-08-12T15:47:04.333+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-12T15:47:04.339+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): spark_hourly_change> on 2025-08-12 14:00:00+00:00
[2025-08-12T15:47:04.345+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crypto_hourly_pipeline', 'spark_hourly_change', 'scheduled__2025-08-12T14:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/crypto_pipeline.py', '--cfg-path', '/tmp/tmp2fuu7isb']
[2025-08-12T15:47:04.350+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask spark_hourly_change
[2025-08-12T15:47:04.352+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=206) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T15:47:04.356+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-08-12T15:47:04.410+0000] {task_command.py:426} INFO - Running <TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T14:00:00+00:00 [running]> on host 93b3870592ea
[2025-08-12T15:47:04.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_hourly_pipeline' AIRFLOW_CTX_TASK_ID='spark_hourly_change' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T14:00:00+00:00'
[2025-08-12T15:47:04.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T15:47:04.492+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T15:47:04.493+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/project && python spark_hourly_change.py']
[2025-08-12T15:47:04.499+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T15:47:06.497+0000] {subprocess.py:93} INFO - 2025-08-12 15:47:06,496 - INFO - Starting hourly change calculation...
[2025-08-12T15:47:06.538+0000] {subprocess.py:93} INFO - JAVA_HOME is not set
[2025-08-12T15:47:06.613+0000] {subprocess.py:93} INFO - 2025-08-12 15:47:06,612 - ERROR - Hourly change calculation failed: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-08-12T15:47:06.613+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T15:47:06.614+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 176, in <module>
[2025-08-12T15:47:06.614+0000] {subprocess.py:93} INFO -     main()
[2025-08-12T15:47:06.615+0000] {subprocess.py:93} INFO -     ^^^^^^
[2025-08-12T15:47:06.615+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 155, in main
[2025-08-12T15:47:06.615+0000] {subprocess.py:93} INFO -     spark = create_spark_session()
[2025-08-12T15:47:06.616+0000] {subprocess.py:93} INFO -             ^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T15:47:06.616+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 48, in create_spark_session
[2025-08-12T15:47:06.616+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-08-12T15:47:06.616+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^
[2025-08-12T15:47:06.616+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
[2025-08-12T15:47:06.617+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-08-12T15:47:06.617+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T15:47:06.617+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 523, in getOrCreate
[2025-08-12T15:47:06.617+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-08-12T15:47:06.618+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 205, in __init__
[2025-08-12T15:47:06.618+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-08-12T15:47:06.618+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
[2025-08-12T15:47:06.618+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-08-12T15:47:06.619+0000] {subprocess.py:93} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-08-12T15:47:06.619+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
[2025-08-12T15:47:06.619+0000] {subprocess.py:93} INFO -     raise PySparkRuntimeError(
[2025-08-12T15:47:06.619+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-08-12T15:47:06.727+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T15:47:06.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T15:47:06.774+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T15:47:06.783+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_hourly_pipeline, task_id=spark_hourly_change, run_id=scheduled__2025-08-12T14:00:00+00:00, execution_date=20250812T140000, start_date=20250812T154704, end_date=20250812T154706
[2025-08-12T15:47:06.793+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task spark_hourly_change (Bash command failed. The command returned a non-zero exit code 1.; 207)
[2025-08-12T15:47:06.827+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T15:47:06.858+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T15:47:06.859+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
